class: edu.cmu.lti.oaqa.bio.core.retrieval.DefaultRetrievalStrategist
hit-list-size: 1000
server: peace.isri.cs.cmu.edu
port: 21237

persistence-provider: |
  inherit: internal.log-persistence-provider
  