configuration: 
  name: bioqa-development-test
  author: yanfang

persistence-provider:
#  inherit: bioqa.db.cse-persistence-provider  
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: bioqa.collection.decorated-collection-reader
  dataset: TRECGEN06
  file: /input/trecgen06.txt

#collection-reader:
#  inherit: bioqa.db.collection-reader
#  dataset: BIO-COMBINED
#  sequence-start: 160
#  sequence-end: 187
#  sequence-end: 160
  
pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
      - inherit: default.keyterm.default

  - inherit: jdbc.sqlite.cse.phase 
    name: pos-tagger
    options: |
      - inherit: bioqa.keyterm.lingpipe-hmm

  - inherit: jdbc.sqlite.cse.phase
    name: name-entity-recognizer
    options: |
      - inherit: bioqa.keyterm.lingpipe-abbreviation
      #- inherit: bioqa.keyterm.lingpipe

  #- inherit: jdbc.sqlite.cse.phase
   # name: name-entity-recognizer
    #options: |
     # - inherit: bioqa.keyterm.syn-abbreviation-longform

  - inherit: jdbc.sqlite.cse.phase
    name: name-entity-recognizer
    options: |
      - inherit: bioqa.keyterm.syn-lexical-variants

  - inherit: jdbc.sqlite.cse.phase
    name: restore
    options: |
      - inherit: bioqa.keyterm.restore
      #- inherit: bioqa.keyterm.restore_before


  #- inherit: jdbc.sqlite.cse.phase
   # name: synonyms
    #options: |
     # - inherit: bioqa.keyterm.kb.mesh

  #- inherit: jdbc.sqlite.cse.phase
   # name: synonyms
    #options: |
     # - inherit: bioqa.keyterm.kb.entrezgene

#  - inherit: jdbc.sqlite.cse.phase
#    name: synonyms
#    options: |
#      - inherit: bioqa.keyterm.kb.umls
 
  #- inherit: jdbc.sqlite.cse.phase
   # name: store
    #options: |
     # - inherit: bioqa.keyterm.restore

  #- inherit: jdbc.sqlite.cse.phase
   # name: store
    #options: |
     # - inherit: bioqa.keyterm.io.backup

  - inherit: jdbc.sqlite.cse.phase
    name: keyterm-refiner
    lazy-load-options: true
    options: |
      - inherit: bioqa.keyterm.keyterm-refiner

  - inherit: jdbc.sqlite.cse.phase
    name: retrieval-strategist
    options: | 
      - inherit: bioqa.retrieval.BasicIndriRetrieval

  - inherit: jdbc.sqlite.cse.phase
    name: passage-extractor
    options: | 
      - inherit: bioqa.ie.IndriLegalSpan

  #- inherit: jdbc.sqlite.cse.phase
   # name: retrieval-strategist
    #options: |
     # - inherit: bioqa.retrieval.io.restore
      
  #- inherit: jdbc.sqlite.cse.phase
   # name: passage-extractor
    #options: |
     # - inherit: default.ie.default

#  - inherit: jdbc.sqlite.cse.phase 
#    name: passage-span
#    lazy-load-options: true
#    options: |
#      - inherit: bioqa.ie.span.important-sentence@peace
#      #- inherit: base.noop

#  - inherit: jdbc.sqlite.cse.phase 
#    name: passage-rank
#    lazy-load-options: true
#    options: |
#      - inherit: bioqa.ie.rank.proximity@peace
#      #- inherit: base.noop
      
#  - inherit: jdbc.sqlite.cse.phase 
#    name: score-combine
#    options: |
#      - inherit: bioqa.ie.rank.combine
#      #- inherit: base.noop

#  - inherit: jdbc.sqlite.cse.phase 
#    name: passage-overlap
#    options: |
#      - inherit: bioqa.ie.overlap.filter
#      #- inherit: base.noop

#  - inherit: jdbc.eval.retrieval-aggregator-consumer      
#  - inherit: helloqa.eval.passage-map-aggregator-consumer      

  - inherit: internal.eval.cse-retrieval-aggregator-consumer
  - inherit: internal.eval.cse-passage-map-aggregator-consumer

    
#post-process: 

#  - inherit: jdbc.eval.retrieval-evaluator-consumer
#  - inherit: report.csv-report-generator
#    builders: |
#      - inherit: jdbc.report.f-measure-report-component
          
#  - inherit: helloqa.eval.passage-map-evaluator-consumer
#  - inherit: report.csv-report-generator
#    builders: |
#      - inherit: helloqa.report.map-report-component

post-process: 
  - inherit: internal.eval.cse-retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: internal.report.f-measure-report-component
  - inherit: internal.eval.cse-passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: internal.report.map-report-component
  
