configuration: 
  name: bioqa-development-test
  author: yanfang

persistence-provider:
  inherit: bioqa.db.cse-persistence-provider
  
async-configuration:
  inherit: bioqa.async.cse-broker 

collection-reader:
  inherit: bioqa.db.collection-reader-consumer
  dataset: BIO-COMBINED
  sequence-start: 160
  sequence-end: 187
  
pipeline:
  - inherit: internal.cse.phase  
    name: keyterm-extractor
    option-timeout: 2
    options: |
      - inherit: default.keyterm.default

  - inherit: internal.cse.phase 
    name: pos-tagger
    option-timeout: 2
    options: |
      - inherit: bioqa.keyterm.lingpipe-hmm

  - inherit: internal.cse.phase
    name: name-entity-recognizer
    option-timeout: 2
    options: |
      - inherit: bioqa.keyterm.lingpipe-abbreviation

  - inherit: internal.cse.phase
    name: name-entity-recognizer
    option-timeout: 2
    options: |
      - inherit: bioqa.keyterm.syn-lexical-variants

  - inherit: internal.cse.phase
    name: restore
    option-timeout: 2
    options: |
      - inherit: bioqa.keyterm.restore

  - inherit: internal.cse.phase
    name: synonyms
    option-timeout: 2
    options: |
      - inherit: bioqa.keyterm.kb.umls
      
  - inherit: internal.cse.phase
    name: experiment2-comparation
    option-timeout: 8
    options: |
      # BEST-PERFORMANCE
      - pipeline:
        - inherit: bioqa.keyterm.keyterm-refiner
        - inherit: bioqa.retrieval.BasicIndriRetrieval
        - inherit: bioqa.ie.IndriLegalSpan
        - inherit: bioqa.ie.span.important-sentence@peace
        - inherit: bioqa.ie.rank.proximity@peace
        - inherit: bioqa.ie.rank.combine
        - inherit: bioqa.ie.overlap.filter
      # SYNONYM-EXPANSION
      - pipeline:
        - inherit: bioqa.keyterm.keyterm-refiner-synonym-expansion
        - inherit: bioqa.retrieval.BasicIndriRetrieval
        - inherit: bioqa.ie.IndriLegalSpan
        - inherit: bioqa.ie.span.important-sentence@peace
        - inherit: bioqa.ie.rank.proximity@peace
        - inherit: bioqa.ie.rank.combine
        - inherit: bioqa.ie.overlap.filter

  - inherit: internal.eval.cse-retrieval-aggregator-consumer
  - inherit: internal.eval.cse-passage-map-aggregator-consumer

post-process: 
  - inherit: internal.eval.cse-retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: internal.report.f-measure-report-component
  - inherit: internal.eval.cse-passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: internal.report.map-report-component
  

  